name: alloy-build

# Docs
# - https://gist.github.com/faph/20331648cdc0b492eba0f4d83f69eaa5
# - https://github.com/spotify/dockerfile-maven
# - https://github.com/actions/setup-java

on:
  push:
    branches:
      - build
    paths:
      - '.github/workflows/build.yml'
      - 'build-sample/**'
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - 'build-sample/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 13
        server-id: ossrh
        server-username: CI_DEPLOY_USERNAME
        server-password: CI_DEPLOY_PASSWORD
    - name: Configure git
      run: |
        git config --global committer.email "infra@finos.org"
        git config --global committer.name "FINOS Admin"
        git config --global author.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global author.name "${GITHUB_ACTOR}"
    - name: Run mvn tests
      run: |
        cd build-sample
        mvn test
    - name: Deploy SNAPSHOT version to oss.sonatype.org (and submit metrics to sonarcloud.io)
      run: |
        cd build-sample
        # TODO - fix deploy, fails with 401
        mvn deploy -Psonar,docker
        # mvn install -Psonar,docker
      env:
        CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
        CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}        
  